# Generated by Django 3.2.6 on 2021-09-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0005_auto_20210901_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline_time',
            field=models.DateTimeField(verbose_name='2021-09-01T16.59'),
        ),
    ]
