# Generated by Django 3.2.6 on 2021-09-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0007_alter_todo_deadline_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline_time',
            field=models.DateTimeField(verbose_name='2021-09-02T12.36'),
        ),
    ]
