# Generated by Django 3.2.6 on 2021-09-03 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0008_alter_todo_deadline_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 3, 7, 9, 13, 111531)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 3, 7, 9, 13, 111531)),
        ),
    ]
