# Generated by Django 3.2.6 on 2021-09-03 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0009_auto_20210903_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 7, 10, 32, 811100)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 3, 7, 10, 32, 811100)),
        ),
    ]
