# Generated by Django 3.2.6 on 2021-09-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0012_auto_20210903_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(default=123, max_length=10),
        ),
    ]
