# Generated by Django 3.2.6 on 2021-09-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0015_alter_todo_deadline_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
