# Generated by Django 3.2.6 on 2021-09-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0017_alter_todo_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
