# Generated by Django 3.2.6 on 2021-09-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0020_alter_todo_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
